const state={selectedGroup:'chest',selectedExercise:'ベンチプレス',selectedDate:'2026-04-05',selectedHistoryDate:'2026-03-31',selectedHistoryRange:'daily',selectedCalendarMetric:'total',setRecords:{...window.sampleSetRecords,...JSON.parse(localStorage.getItem('liftflow-set-records')||'{}')},restRemaining:120,restTimer:null,rootMode:'record'};
const el={recordRoot:document.getElementById('record-root'),historyRoot:document.getElementById('history-root'),muscleGroupSelect:document.getElementById('muscleGroupSelect'),exerciseSelect:document.getElementById('exerciseSelect'),exerciseName:document.getElementById('exerciseName'),lastPerformed:document.getElementById('lastPerformed'),goalSets:document.getElementById('goalSets'),goalReps:document.getElementById('goalReps'),aiSuggestionText:document.getElementById('aiSuggestionText'),muscleNames:document.getElementById('muscleNames'),restDisplay:document.getElementById('restDisplay'),restMin:document.getElementById('restMin'),restSec:document.getElementById('restSec'),restStart:document.getElementById('restStart'),restReset:document.getElementById('restReset'),setNumber:document.getElementById('setNumber'),repNumber:document.getElementById('repNumber'),weightNumber:document.getElementById('weightNumber'),addSetBtn:document.getElementById('addSetBtn'),setRecords:document.getElementById('setRecords'),recordCard:document.getElementById('recordCard'),timerCard:document.getElementById('timerCard'),suggestionCard:document.getElementById('suggestionCard'),proteinGoal:document.getElementById('proteinGoal'),waterGoal:document.getElementById('waterGoal'),sleepGoal:document.getElementById('sleepGoal'),carbGoal:document.getElementById('carbGoal'),dailyAiText:document.getElementById('dailyAiText'),calendarGrid:document.getElementById('calendarGrid'),calendarMetricSelect:document.getElementById('calendarMetricSelect'),summaryVolume:document.getElementById('summaryVolume'),summaryAvgWeight:document.getElementById('summaryAvgWeight'),summaryReps:document.getElementById('summaryReps'),summarySets:document.getElementById('summarySets'),historyComboCanvas:document.getElementById('historyComboCanvas'),trainingTrendCanvas:document.getElementById('trainingTrendCanvas')};
const {getSetKey,dateDiffDays,flashGold,drawDualChart}=window.helpers;
const saveLocal=()=>localStorage.setItem('liftflow-set-records',JSON.stringify(state.setRecords));
const getRecordsForDate=date=>Object.keys(state.setRecords).filter(k=>k.startsWith(`${date}__`)).flatMap(k=>{const exercise=k.split('__')[1];return state.setRecords[k].map(r=>({...r,exercise}))});
function matchFilter(exercise,filter){const g=window.EXERCISES[exercise]?.group;if(filter==='total')return true;if(filter==='upper')return['chest','shoulder','back','arms'].includes(g);if(filter==='lower')return g==='legs';if(filter==='legs')return g==='legs';return g===filter}
const getTotalVolumeForDate=(date,filter='total')=>getRecordsForDate(date).filter(r=>matchFilter(r.exercise,filter)).reduce((s,r)=>s+r.reps*r.weight,0);
const getAvgWeightForDate=date=>{const rs=getRecordsForDate(date);return rs.length?Math.round((rs.reduce((s,r)=>s+r.weight,0)/rs.length)*10)/10:0};
const getTotalRepsForDate=date=>getRecordsForDate(date).reduce((s,r)=>s+r.reps,0);
const getSetCountForDate=date=>getRecordsForDate(date).length;
const getAllDatesWithTraining=()=>[...new Set(Object.keys(state.setRecords).map(k=>k.split('__')[0]))].sort();
function makeSuggestion(exerciseName){const ex=window.EXERCISES[exerciseName],days=dateDiffDays(state.selectedDate,ex.lastDate),goalSets=3,goalReps=['サイドレイズ','ダンベルフライ'].includes(exerciseName)?'10-15':exerciseName==='懸垂'?'6-10':'5-8',tone=days<2?'Recovery Focus':'Progressive Load',text=days<2?'Previous session is close, so today prioritizes quality and repeatability over pushing load.':'Recent trend is stable, so today aims to keep quality high and slightly raise total work.';return{goalSets,goalReps,tone,text}}
function makeRecoverySuggestion(){const todayVol=getTotalVolumeForDate(state.selectedDate),protein=todayVol>0?140:120,water=todayVol>0?3.0:2.5,sleep=todayVol>0?8.0:7.5,carb=todayVol>1800?5:todayVol>1000?4:3;return{protein,water,sleep,carb,text:todayVol>0?'Based on today’s logged work, prioritize carbs, hydration, and protein for recovery.':'Base recovery target for a lighter or non-training day.'}}
function renderExerciseOptions(){el.exerciseSelect.innerHTML='';Object.entries(window.EXERCISES).filter(([,v])=>v.group===state.selectedGroup).forEach(([name])=>{const opt=document.createElement('option');opt.value=name;opt.textContent=name;el.exerciseSelect.appendChild(opt)});if(!window.EXERCISES[state.selectedExercise]||window.EXERCISES[state.selectedExercise].group!==state.selectedGroup){state.selectedExercise=el.exerciseSelect.value||Object.keys(window.EXERCISES)[0]}}
function renderBodyMap(){document.querySelectorAll('#frontBody [id], #backBody [id]').forEach(n=>{if(n.tagName!=='svg')n.setAttribute('fill','#1f2937')});window.EXERCISES[state.selectedExercise].target.forEach(id=>{const n=document.getElementById(id);if(n)n.setAttribute('fill','#ef4444')})}
function renderSetRecords(){const rs=state.setRecords[getSetKey(state.selectedDate,state.selectedExercise)]||[];if(!rs.length){el.setRecords.innerHTML='<div class="sub">No records yet.</div>';return}el.setRecords.innerHTML=rs.map((r,i)=>`<div class="record-item"><div><div class="record-main">${r.set} set / ${r.reps} reps / ${r.weight}kg</div><div class="record-sub">Volume ${r.reps*r.weight}</div></div><button data-remove="${i}" style="width:auto;">Delete</button></div>`).join('');el.setRecords.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{const arr=state.setRecords[getSetKey(state.selectedDate,state.selectedExercise)]||[];arr.splice(Number(btn.dataset.remove),1);state.setRecords[getSetKey(state.selectedDate,state.selectedExercise)]=arr;saveLocal();renderSetRecords();renderTrainingTrend();renderHistorySummary();renderCalendar()}))}
function renderTraining(){const ex=window.EXERCISES[state.selectedExercise],sg=makeSuggestion(state.selectedExercise),rg=makeRecoverySuggestion();el.exerciseName.textContent=state.selectedExercise;el.lastPerformed.textContent=`Previous: ${ex.lastDate} / ${sg.tone}`;el.goalSets.textContent=sg.goalSets;el.goalReps.textContent=sg.goalReps;el.aiSuggestionText.textContent=sg.text;el.muscleNames.innerHTML=ex.muscles.map(m=>`<span class="muscle-pill">${m}</span>`).join('');el.proteinGoal.textContent=`${rg.protein}g`;el.waterGoal.textContent=`${rg.water}L`;el.sleepGoal.textContent=`${rg.sleep}h`;el.carbGoal.textContent=`${rg.carb}合`;el.dailyAiText.textContent=rg.text;renderSetRecords();renderBodyMap();renderTrainingTrend()}
function renderTrainingTrend(){const ds=getAllDatesWithTraining().slice(-6),left=ds.map(d=>({label:`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`,value:getTotalVolumeForDate(d)})),right=ds.map(d=>({label:`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`,value:getAvgWeightForDate(d)}));drawDualChart(el.trainingTrendCanvas,left,right)}
function aggregateSeries(range){const ds=getAllDatesWithTraining();if(!ds.length)return{left:[],right:[]};if(range==='daily')return{left:ds.map(d=>({label:`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`,value:getTotalVolumeForDate(d)})),right:ds.map(d=>({label:`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`,value:getAvgWeightForDate(d)}))};if(range==='weekly'){const weeks={};ds.forEach(d=>{const dt=new Date(d+'T00:00:00'),start=new Date(dt);start.setDate(dt.getDate()-dt.getDay());const key=`${start.getMonth()+1}/${start.getDate()}`;if(!weeks[key])weeks[key]={volume:0,avgList:[]};weeks[key].volume+=getTotalVolumeForDate(d);const avg=getAvgWeightForDate(d);if(avg)weeks[key].avgList.push(avg)});const keys=Object.keys(weeks);return{left:keys.map(k=>({label:k,value:weeks[k].volume})),right:keys.map(k=>({label:k,value:Math.round((weeks[k].avgList.reduce((a,b)=>a+b,0)/Math.max(weeks[k].avgList.length,1))*10)/10}))}}const months={};ds.forEach(d=>{const dt=new Date(d+'T00:00:00'),key=`${dt.getMonth()+1}月`;if(!months[key])months[key]={volume:0,avgList:[]};months[key].volume+=getTotalVolumeForDate(d);const avg=getAvgWeightForDate(d);if(avg)months[key].avgList.push(avg)});const keys=Object.keys(months);return{left:keys.map(k=>({label:k,value:months[k].volume})),right:keys.map(k=>({label:k,value:Math.round((months[k].avgList.reduce((a,b)=>a+b,0)/Math.max(months[k].avgList.length,1))*10)/10}))}}
function renderCalendar(){const year=2026,month=2,firstDay=new Date(year,month,1).getDay(),lastDate=new Date(year,month+1,0).getDate();el.calendarGrid.innerHTML='';['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(d=>{const node=document.createElement('div');node.className='dow';node.textContent=d;el.calendarGrid.appendChild(node)});for(let i=0;i<firstDay;i++){const blank=document.createElement('div');blank.className='day empty';el.calendarGrid.appendChild(blank)}for(let d=1;d<=lastDate;d++){const dateStr=`2026-03-${String(d).padStart(2,'0')}`,metric=getTotalVolumeForDate(dateStr,state.selectedCalendarMetric),btn=document.createElement('button');btn.className='day';if(metric>0)btn.classList.add('partial');if(dateStr===state.selectedHistoryDate)btn.classList.add('active');btn.innerHTML=`<div class="day-num">${d}</div><div class="day-metric">${metric||'-'}</div>`;btn.addEventListener('click',()=>{state.selectedHistoryDate=dateStr;renderHistorySummary();renderCalendar()});el.calendarGrid.appendChild(btn)}}
function renderHistorySummary(){const date=state.selectedHistoryDate;el.summaryVolume.textContent=getTotalVolumeForDate(date)||'-';el.summaryAvgWeight.textContent=getAvgWeightForDate(date)||'-';el.summaryReps.textContent=getTotalRepsForDate(date)||'-';el.summarySets.textContent=getSetCountForDate(date)||'-';const aggregated=aggregateSeries(state.selectedHistoryRange);drawDualChart(el.historyComboCanvas,aggregated.left,aggregated.right)}
function renderRootMode(){document.querySelectorAll('.tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===state.rootMode));el.recordRoot.classList.toggle('hidden',state.rootMode!=='record');el.historyRoot.classList.toggle('hidden',state.rootMode!=='history')}
function syncRestFromInput(){state.restRemaining=Math.max(0,Number(el.restMin.value||0)*60+Number(el.restSec.value||0));renderRest()}
function renderRest(){const m=Math.floor(state.restRemaining/60),s=state.restRemaining%60;el.restDisplay.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function notifyRestEnd(){try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(AudioCtx){const ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=720;osc.connect(gain);gain.connect(ctx.destination);gain.gain.setValueAtTime(0.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.08,ctx.currentTime+0.02);gain.gain.exponentialRampToValueAtTime(0.0001,ctx.currentTime+0.35);osc.start();osc.stop(ctx.currentTime+0.36)}}catch(e){}flashGold(el.timerCard)}
function startRestTimer(){clearInterval(state.restTimer);if(state.restRemaining<=0)syncRestFromInput();flashGold(el.timerCard);state.restTimer=setInterval(()=>{state.restRemaining-=1;renderRest();if(state.restRemaining<=0){clearInterval(state.restTimer);state.restTimer=null;notifyRestEnd()}},1000)}
function addSetRecord(){const key=getSetKey(state.selectedDate,state.selectedExercise),arr=state.setRecords[key]||[];arr.push({set:Number(el.setNumber.value),reps:Number(el.repNumber.value),weight:Number(el.weightNumber.value)});state.setRecords[key]=arr.sort((a,b)=>a.set-b.set);saveLocal();el.setNumber.value=String(Math.min(Number(el.setNumber.value)+1,8));renderSetRecords();renderTrainingTrend();renderHistorySummary();renderCalendar();flashGold(el.recordCard);syncRestFromInput();startRestTimer()}
function initSelectors(){window.MUSCLE_GROUPS.forEach(g=>{const opt=document.createElement('option');opt.value=g.value;opt.textContent=g.label;el.muscleGroupSelect.appendChild(opt)});renderExerciseOptions();for(let i=1;i<=8;i++)el.setNumber.insertAdjacentHTML('beforeend',`<option value="${i}">${i} set</option>`);for(let i=1;i<=20;i++)el.repNumber.insertAdjacentHTML('beforeend',`<option value="${i}">${i} reps</option>`);for(let i=0;i<=220;i+=2.5)el.weightNumber.insertAdjacentHTML('beforeend',`<option value="${i}">${i}kg</option>`);el.muscleGroupSelect.value=state.selectedGroup;el.exerciseSelect.value=state.selectedExercise}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{state.rootMode=tab.dataset.tab;renderRootMode();if(state.rootMode==='history'){renderCalendar();renderHistorySummary()}}));
document.querySelectorAll('.segment').forEach(seg=>seg.addEventListener('click',()=>{state.selectedHistoryRange=seg.dataset.range;document.querySelectorAll('.segment').forEach(s=>s.classList.toggle('active',s.dataset.range===state.selectedHistoryRange));renderHistorySummary()}));
el.calendarMetricSelect.addEventListener('change',e=>{state.selectedCalendarMetric=e.target.value;renderCalendar()});
el.muscleGroupSelect.addEventListener('change',e=>{state.selectedGroup=e.target.value;renderExerciseOptions();el.exerciseSelect.value=state.selectedExercise;renderTraining();flashGold(el.suggestionCard)});
el.exerciseSelect.addEventListener('change',e=>{state.selectedExercise=e.target.value;renderTraining();flashGold(el.suggestionCard)});
el.restMin.addEventListener('input',syncRestFromInput);el.restSec.addEventListener('input',syncRestFromInput);el.restStart.addEventListener('click',startRestTimer);el.restReset.addEventListener('click',()=>{clearInterval(state.restTimer);state.restTimer=null;syncRestFromInput();flashGold(el.timerCard)});el.addSetBtn.addEventListener('click',addSetRecord);
initSelectors();syncRestFromInput();renderRootMode();renderTraining();renderCalendar();renderHistorySummary();
